spring.application.name=movie-watchlist-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_watchlist
spring.datasource.username=postgres
spring.datasource.password=sql2003

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# JWT Secret Key
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbkFuZFZhbGlkYXRpb24xMjM0NTY3ODkw

# JWT Expiration (24 Hours)
jwt.expiration=86400000